# TWRP Configuration
TW_THEME := portrait_hdpi
TW_EXTRA_LANGUAGES := true
TW_INPUT_BLACKLIST := "hbtp_vm"
TW_DEFAULT_LANGUAGE := id
TW_EXTRA_LANGUAGES := false
TW_USE_TOOLBOX := true
TW_NO_LEGACY_PROPS := true
TW_HAS_DOWNLOAD_MODE := true
TW_SCREEN_BLANK_ON_BOOT := true

# Include
TW_INCLUDE_FASTBOOTD := true
TW_INCLUDE_LIBRESETPROP := true
TW_INCLUDE_RESETPROP := true
TW_INCLUDE_REPACKTOOLS := true
TW_INCLUDE_NTFS_3G := true
TW_INCLUDE_PYTHON := true

# Exclude
TW_EXCLUDE_DEFAULT_USB_INIT := true
TW_EXCLUDE_APEX := true
TW_BACKUP_EXCLUSIONS := /data/fonts

# Product
PRODUCT_FULL_TREBLE := true

# Tw-StatusBar
TW_STATUS_ICONS_ALIGN := center
TW_CUSTOM_CPU_POS := "300"
TW_CUSTOM_CLOCK_POS := "70"
TW_CUSTOM_BATTERY_POS := "790"

# Debug
TWRP_INCLUDE_LOGCAT := true
TARGET_USES_LOGD := true

# OrangeFox Configuration
FOX_VIRTUAL_AB_DEVICE := true
FOX_BUILD_DEVICE := a14m
OF_DEFAULT_LANG := id
OF_KEEP_DM_VERITY := true
OF_USE_SYSTEM_FINGERPRINT := true
OF_FLASHLIGHT_ENABLE := true
OF_FL_PATH1 := /sys/class/flashlight_core/flashlight

# Ofx-StatusBar
OF_HIDE_NOTCH := true
OF_CLOCK_POS := 1
OF_STATUS_INDENT_LEFT := 50
OF_STATUS_INDENT_RIGHT := 50

# PBRP Configuration
PBRP_DEVICE := RMX3710
PB_DISABLE_DEFAULT_DM_VERITY := true
PB_TORCH_PATH := "/sys/class/flashlight_core/flashlight"
PB_TORCH_MAX_BRIGHTNESS := 1

# Maintainer
BOARD_MAINTAINER_NAME := A14m-Aflahal
TW_DEVICE_VERSION := $(BOARD_MAINTAINER_NAME)
OF_MAINTAINER := $(BOARD_MAINTAINER_NAME)
PB_MAIN_VERSION := $(BOARD_MAINTAINER_NAME)
